from langchain_core.messages import HumanMessage

from app.graphs import workflow as workflow_module


class ChatService:

    async def send_message(
        self,
        thread_id: str,
        message: str
    ):

        config = {
            "configurable": {
                "thread_id": thread_id
            }
        }

        result = await workflow_module.workflow.ainvoke(
            {
                "messages": [
                    HumanMessage(
                        content=message
                    )
                ]
            },
            config=config
        )

        return result["messages"][-1].content

    async def get_history(self, thread_id: str):

        config = {
            "configurable": {
                "thread_id": thread_id
            }
        }
        state = await workflow_module.workflow.aget_state(
            config
        )

        return state.values.get(
            "messages",
            []
        )

    async def stream_message(
        self,
        thread_id: str,
        message: str
    ):
        """
        Yields plain text tokens as they're generated by the LLM.
        Filters to the 'chat' node so only real assistant content
        gets forwarded (no state/metadata noise).
        """

        config = {
            "configurable": {
                "thread_id": thread_id
            }
        }

        async for chunk, metadata in workflow_module.workflow.astream(
            {
                "messages": [
                    HumanMessage(
                        content=message
                    )
                ]
            },
            config=config,
            stream_mode="messages"
        ):
            if metadata.get("langgraph_node") == "chat" and chunk.content:
                yield chunk.content


chat_service = ChatService()